// packages/db/prisma/seed.ts
//
// Synthetic seed data for the `products` table (task A5). ~30 real plant
// species with plausible HUF pricing and genuine botanical facts backing
// the pet_safe / kid_safe / air_purifying flags (ASPCA toxic-plant list,
// NASA Clean Air Study, common horticultural knowledge).
//
// Run via: pnpm --filter db exec prisma db seed
// (wired up in ../prisma.config.ts -> migrations.seed, Prisma 7 style)

import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '../generated/client/index.js';

// Prisma 7 requires an explicit driver adapter (no bundled query engine
// binary) — see prisma.config.ts, which loads DATABASE_URL from the root
// .env the same way for migrate/db seed.
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

type SeedProduct = {
  name: string;
  latinName: string;
  category:
    | 'szobanövény'
    | 'kerti'
    | 'pozsgás'
    | 'kaktusz'
    | 'fűszer'
    | 'fa-cserje'
    | 'lógó'
    | 'virágzó';
  location: 'beltéri' | 'kültéri' | 'mindkettő';
  price: number;
  salePrice: number | null;
  stock: number;
  light: 'árnyék' | 'alacsony' | 'közepes' | 'erős' | 'direkt nap';
  watering: 'ritka' | 'közepes' | 'gyakori' | 'állandóan nedves';
  difficulty: 'kezdő' | 'haladó' | 'profi';
  currentHeightCm: number;
  maxHeightCm: number;
  currentPotCm: number;
  petSafe: boolean;
  kidSafe: boolean;
  airPurifying: boolean;
  rating: number;
  reviewsCount: number;
  description: string;
};

const products: SeedProduct[] = [
  {
    name: 'Szörnyeteg fikusz (Monstera)',
    latinName: 'Monstera deliciosa',
    category: 'szobanövény',
    location: 'beltéri',
    price: 8990,
    salePrice: null,
    stock: 24,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    currentHeightCm: 60,
    maxHeightCm: 300,
    currentPotCm: 21,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.7,
    reviewsCount: 312,
    description:
      'Az egyik legnépszerűbb szobanövény jellegzetes, áttört levelekkel. Gyorsan növő, mutatós díszlevelű faj, amely félárnyékos, világos helyet kedvel közvetlen napfény nélkül.',
  },
  {
    name: 'Sansevieria (kardliliom)',
    latinName: 'Sansevieria trifasciata',
    category: 'szobanövény',
    location: 'beltéri',
    price: 4490,
    salePrice: 3490,
    stock: 40,
    light: 'alacsony',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 35,
    maxHeightCm: 90,
    currentPotCm: 14,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.8,
    reviewsCount: 501,
    description:
      'Rendkívül igénytelen, szinte elpusztíthatatlan növény, amely heteken át elvan öntözés nélkül is. Kiváló választás kezdőknek és sötétebb irodai sarkokba.',
  },
  {
    name: 'Hegedűlevelű fikusz',
    latinName: 'Ficus lyrata',
    category: 'szobanövény',
    location: 'beltéri',
    price: 15990,
    salePrice: null,
    stock: 12,
    light: 'erős',
    watering: 'közepes',
    difficulty: 'haladó',
    currentHeightCm: 120,
    maxHeightCm: 250,
    currentPotCm: 26,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.3,
    reviewsCount: 178,
    description:
      'Nagy, hegedű alakú fényes levelei igazi dísze bármely nappalinak. Érzékeny a hirtelen helyváltoztatásra és a túlöntözésre, ezért kezdőknek kihívást jelenthet.',
  },
  {
    name: 'Zöldliliom (pókliliom)',
    latinName: 'Chlorophytum comosum',
    category: 'lógó',
    location: 'beltéri',
    price: 2490,
    salePrice: null,
    stock: 55,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    currentHeightCm: 25,
    maxHeightCm: 60,
    currentPotCm: 12,
    petSafe: true,
    kidSafe: true,
    airPurifying: true,
    rating: 4.9,
    reviewsCount: 402,
    description:
      "Klasszikus, könnyen nevelhető lógó növény, amely oldalhajtásokon apró 'pókocskákat' nevel. Háziállatok számára is biztonságos, légtisztító hatású.",
  },
  {
    name: 'Echeveria (rózsapozsgás)',
    latinName: 'Echeveria elegans',
    category: 'pozsgás',
    location: 'mindkettő',
    price: 1690,
    salePrice: null,
    stock: 60,
    light: 'erős',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 8,
    maxHeightCm: 15,
    currentPotCm: 8,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.6,
    reviewsCount: 89,
    description:
      'Rózsa alakú, kékes-zöld húsos levelű pozsgás, amely napos ablakpárkányon vagy erkélyen érzi jól magát. Mérgezéstől mentes, gyerekszobába is ajánlott.',
  },
  {
    name: 'Aranygömb kaktusz',
    latinName: 'Echinocactus grusonii',
    category: 'kaktusz',
    location: 'beltéri',
    price: 3990,
    salePrice: null,
    stock: 18,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 12,
    maxHeightCm: 60,
    currentPotCm: 14,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.5,
    reviewsCount: 63,
    description:
      'Gömbölyű, aranysárga tüskékkel borított látványos kaktuszfaj. Nem mérgező, de éles tüskéi miatt óvatosan kezelendő. Igazi napimádó.',
  },
  {
    name: 'Valódi aloe (aloe vera)',
    latinName: 'Aloe vera',
    category: 'pozsgás',
    location: 'mindkettő',
    price: 2290,
    salePrice: 1790,
    stock: 45,
    light: 'erős',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 18,
    maxHeightCm: 50,
    currentPotCm: 13,
    petSafe: false,
    kidSafe: false,
    airPurifying: false,
    rating: 4.4,
    reviewsCount: 210,
    description:
      'Húsos, géltartalmú levelei miatt közkedvelt gyógynövény, ugyanakkor macskákra és kutyákra mérgező, ezért háziállatos otthonokban körültekintéssel ültetendő.',
  },
  {
    name: 'Zamioculcas (dollárfa)',
    latinName: 'Zamioculcas zamiifolia',
    category: 'szobanövény',
    location: 'beltéri',
    price: 5990,
    salePrice: null,
    stock: 30,
    light: 'alacsony',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 40,
    maxHeightCm: 100,
    currentPotCm: 17,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.7,
    reviewsCount: 267,
    description:
      'Fényes, sötétzöld levelei és rendkívüli szárazságtűrése miatt kedvelt irodai növény. Kalcium-oxalátot tartalmaz, lenyelve irritálhatja a szájüreget.',
  },
  {
    name: 'Aranyfüggő (pothos)',
    latinName: 'Epipremnum aureum',
    category: 'lógó',
    location: 'beltéri',
    price: 2990,
    salePrice: null,
    stock: 48,
    light: 'alacsony',
    watering: 'közepes',
    difficulty: 'kezdő',
    currentHeightCm: 30,
    maxHeightCm: 200,
    currentPotCm: 13,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.8,
    reviewsCount: 356,
    description:
      'Rendkívül tűrőképes, gyorsan futó lógó növény, amely szinte bármilyen fényviszonyt elvisel. Levelei enyhén mérgezőek, ezért kutyás, macskás háztartásban magasra érdemes helyezni.',
  },
  {
    name: 'Fátyolvirág (spatifillum)',
    latinName: 'Spathiphyllum wallisii',
    category: 'virágzó',
    location: 'beltéri',
    price: 4990,
    salePrice: null,
    stock: 26,
    light: 'árnyék',
    watering: 'gyakori',
    difficulty: 'kezdő',
    currentHeightCm: 35,
    maxHeightCm: 70,
    currentPotCm: 15,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.6,
    reviewsCount: 289,
    description:
      'Fehér, torokvirág alakú fellevelekkel díszítő, árnyéktűrő szobanövény. Az egyik legjobb légtisztító faj, de kalcium-oxalát tartalma miatt mérgező lenyelve.',
  },
  {
    name: 'Sárkányfa (Dracaena marginata)',
    latinName: 'Dracaena marginata',
    category: 'fa-cserje',
    location: 'beltéri',
    price: 9990,
    salePrice: null,
    stock: 15,
    light: 'közepes',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 90,
    maxHeightCm: 200,
    currentPotCm: 22,
    petSafe: false,
    kidSafe: true,
    airPurifying: true,
    rating: 4.5,
    reviewsCount: 134,
    description:
      'Karcsú törzsű, pálmaszerű dísznövény, amely jól tűri a szárazságot és a félárnyékot. Kutyákra és macskákra mérgező lehet, emberi fogyasztásra viszont alacsony kockázatú.',
  },
  {
    name: 'Bostoni páfrány',
    latinName: 'Nephrolepis exaltata',
    category: 'lógó',
    location: 'beltéri',
    price: 3490,
    salePrice: null,
    stock: 22,
    light: 'közepes',
    watering: 'gyakori',
    difficulty: 'haladó',
    currentHeightCm: 40,
    maxHeightCm: 80,
    currentPotCm: 17,
    petSafe: true,
    kidSafe: true,
    airPurifying: true,
    rating: 4.2,
    reviewsCount: 97,
    description:
      'Dús, ívelt levélzetű páfrányfaj, amely magas páratartalmat igényel, ezért fürdőszobában vagy rendszeres permetezéssel érzi igazán jól magát.',
  },
  {
    name: 'Bazsalikom',
    latinName: 'Ocimum basilicum',
    category: 'fűszer',
    location: 'mindkettő',
    price: 990,
    salePrice: null,
    stock: 80,
    light: 'direkt nap',
    watering: 'gyakori',
    difficulty: 'kezdő',
    currentHeightCm: 15,
    maxHeightCm: 40,
    currentPotCm: 11,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.6,
    reviewsCount: 445,
    description:
      'Az olasz konyha nélkülözhetetlen fűszernövénye, amely napos, meleg helyen és rendszeres öntözés mellett folyamatosan újranő.',
  },
  {
    name: 'Rozmaring',
    latinName: 'Salvia rosmarinus',
    category: 'fűszer',
    location: 'mindkettő',
    price: 1490,
    salePrice: null,
    stock: 50,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 20,
    maxHeightCm: 100,
    currentPotCm: 13,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.7,
    reviewsCount: 198,
    description:
      'Örökzöld, erőteljesen illatozó mediterrán fűszernövény, amely a szárazságot jobban tűri, mint a túlöntözést. Napos teraszra vagy ablakpárkányra ideális.',
  },
  {
    name: 'Zöld menta',
    latinName: 'Mentha spicata',
    category: 'fűszer',
    location: 'mindkettő',
    price: 890,
    salePrice: 690,
    stock: 65,
    light: 'közepes',
    watering: 'gyakori',
    difficulty: 'kezdő',
    currentHeightCm: 12,
    maxHeightCm: 50,
    currentPotCm: 11,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.5,
    reviewsCount: 156,
    description:
      'Frissítő illatú, gyorsan terjedő fűszer- és teanövény, amely szereti a nedves talajt. Cserépben tartva megakadályozható elszaporodása a kertben.',
  },
  {
    name: 'Levendula',
    latinName: 'Lavandula angustifolia',
    category: 'virágzó',
    location: 'kültéri',
    price: 2190,
    salePrice: null,
    stock: 38,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 25,
    maxHeightCm: 60,
    currentPotCm: 15,
    petSafe: false,
    kidSafe: true,
    airPurifying: false,
    rating: 4.8,
    reviewsCount: 320,
    description:
      'Illatos, lila virágfüzéreivel nyáron beborító mediterrán cserje, amely napos, jól szellőző helyet és mérsékelt öntözést igényel. Nagyobb mennyiségben lenyelve háziállatokra ártalmas lehet.',
  },
  {
    name: 'Borostyán',
    latinName: 'Hedera helix',
    category: 'lógó',
    location: 'mindkettő',
    price: 2990,
    salePrice: null,
    stock: 33,
    light: 'árnyék',
    watering: 'közepes',
    difficulty: 'haladó',
    currentHeightCm: 30,
    maxHeightCm: 150,
    currentPotCm: 14,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.1,
    reviewsCount: 122,
    description:
      'Sötét, fényes levelű kúszónövény, amely kültéren és beltéren egyaránt megél. Levelei mérgezőek, lenyelve hányingert okozhatnak, ezért gyerekektől távol tartandó.',
  },
  {
    name: 'Gumifikusz',
    latinName: 'Ficus elastica',
    category: 'fa-cserje',
    location: 'beltéri',
    price: 7990,
    salePrice: null,
    stock: 20,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    currentHeightCm: 80,
    maxHeightCm: 200,
    currentPotCm: 21,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.4,
    reviewsCount: 145,
    description:
      'Nagy, bőrszerű, fényes levelei miatt kedvelt klasszikus szobanövény. Tejnedve bőrirritációt okozhat, ezért érdemes kesztyűben metszeni.',
  },
  {
    name: 'Kereklevelű kosárka (kalátea)',
    latinName: 'Goeppertia orbifolia',
    category: 'szobanövény',
    location: 'beltéri',
    price: 6490,
    salePrice: null,
    stock: 14,
    light: 'árnyék',
    watering: 'állandóan nedves',
    difficulty: 'profi',
    currentHeightCm: 35,
    maxHeightCm: 60,
    currentPotCm: 17,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.0,
    reviewsCount: 71,
    description:
      'Csíkozott, ezüstös mintázatú dekorleveleivel tűnik ki, de magas páratartalmat és folyamatosan nedves talajt igényel, ami kezdőknek nehézséget okozhat.',
  },
  {
    name: 'Pillangóorchidea',
    latinName: 'Phalaenopsis hybrid',
    category: 'virágzó',
    location: 'beltéri',
    price: 5490,
    salePrice: 4290,
    stock: 28,
    light: 'közepes',
    watering: 'ritka',
    difficulty: 'haladó',
    currentHeightCm: 40,
    maxHeightCm: 60,
    currentPotCm: 12,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.6,
    reviewsCount: 233,
    description:
      'Hónapokig nyíló, elegáns virágzatú orchideafaj, amelyet átlátszó cserépben, ritka, de alapos áztatásos öntözéssel érdemes gondozni.',
  },
  {
    name: 'Fikusz benjamina',
    latinName: 'Ficus benjamina',
    category: 'fa-cserje',
    location: 'beltéri',
    price: 8490,
    salePrice: null,
    stock: 17,
    light: 'erős',
    watering: 'közepes',
    difficulty: 'haladó',
    currentHeightCm: 100,
    maxHeightCm: 300,
    currentPotCm: 24,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.0,
    reviewsCount: 108,
    description:
      'Karcsú ágú, sűrű lombozatú fa, amely érzékenyen reagál a huzatra és a helyváltoztatásra levélhullással. Tejnedve enyhén mérgező háziállatokra.',
  },
  {
    name: 'Pénznövény (jádefa)',
    latinName: 'Crassula ovata',
    category: 'pozsgás',
    location: 'mindkettő',
    price: 2490,
    salePrice: null,
    stock: 42,
    light: 'erős',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 20,
    maxHeightCm: 90,
    currentPotCm: 14,
    petSafe: false,
    kidSafe: true,
    airPurifying: false,
    rating: 4.7,
    reviewsCount: 187,
    description:
      'Fényes, húsos leveleivel és bonsai-szerű elágazásával népszerű, könnyen szaporítható pozsgás. Kutyákra és macskákra enyhén mérgező lehet.',
  },
  {
    name: 'Nyúlfül kaktusz',
    latinName: 'Opuntia microdasys',
    category: 'kaktusz',
    location: 'mindkettő',
    price: 1990,
    salePrice: null,
    stock: 35,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'haladó',
    currentHeightCm: 15,
    maxHeightCm: 40,
    currentPotCm: 12,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.3,
    reviewsCount: 76,
    description:
      'Lapos, nyúlfülre emlékeztető hajtásait apró, horgas szőrtüskék (glochidiumok) borítják, amelyek könnyen a bőrbe fúródnak, ezért kesztyűs kezelést igényel.',
  },
  {
    name: 'Aglaonema (ezüstfátyol)',
    latinName: 'Aglaonema commutatum',
    category: 'szobanövény',
    location: 'beltéri',
    price: 4990,
    salePrice: null,
    stock: 25,
    light: 'alacsony',
    watering: 'közepes',
    difficulty: 'kezdő',
    currentHeightCm: 30,
    maxHeightCm: 60,
    currentPotCm: 15,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.5,
    reviewsCount: 143,
    description:
      'Mintázott, ezüstös-zöld leveleivel gyenge fényviszonyok között is jól teljesítő, igénytelen szobanövény. Nedve irritálhatja a bőrt és a nyálkahártyát.',
  },
  {
    name: 'Szívlevelű filodendron',
    latinName: 'Philodendron hederaceum',
    category: 'lógó',
    location: 'beltéri',
    price: 3290,
    salePrice: null,
    stock: 37,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    currentHeightCm: 25,
    maxHeightCm: 150,
    currentPotCm: 13,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.6,
    reviewsCount: 201,
    description:
      'Szív alakú, fényes levelű, gyorsan futó lógó növény, amely szinte bármilyen beltéri fényviszonyt tolerál. Kalcium-oxalátja miatt lenyelve mérgező.',
  },
  {
    name: 'Elefántlábpálma',
    latinName: 'Beaucarnea recurvata',
    category: 'fa-cserje',
    location: 'beltéri',
    price: 11990,
    salePrice: null,
    stock: 10,
    light: 'erős',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 70,
    maxHeightCm: 180,
    currentPotCm: 22,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.8,
    reviewsCount: 94,
    description:
      'Vízraktározó, jellegzetesen megvastagodott törzse miatt kiválóan tűri az elhanyagolt öntözést. Nem mérgező, biztonságos választás családosoknak is.',
  },
  {
    name: 'Mexikói citrom (Meyer citrom)',
    latinName: "Citrus limon 'Meyer'",
    category: 'kerti',
    location: 'mindkettő',
    price: 13990,
    salePrice: 11990,
    stock: 9,
    light: 'direkt nap',
    watering: 'közepes',
    difficulty: 'profi',
    currentHeightCm: 90,
    maxHeightCm: 200,
    currentPotCm: 30,
    petSafe: false,
    kidSafe: true,
    airPurifying: false,
    rating: 4.4,
    reviewsCount: 58,
    description:
      'Termőképes, illatos virágú citrusfa, amely nyáron a szabadban, télen fagymentes, világos helyiségben teleltethető. Levelei és héja háziállatokra mérgezőek lehetnek.',
  },
  {
    name: 'Karácsonyi kaktusz',
    latinName: 'Schlumbergera truncata',
    category: 'kaktusz',
    location: 'beltéri',
    price: 2690,
    salePrice: null,
    stock: 31,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    currentHeightCm: 20,
    maxHeightCm: 40,
    currentPotCm: 13,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.7,
    reviewsCount: 176,
    description:
      'A sivatagi kaktuszokkal ellentétben ez az epifita faj rendszeres öntözést kedvel, és késő ősszel rózsaszín-piros virágokkal hálálja meg a gondoskodást.',
  },
  {
    name: 'Kerti hortenzia',
    latinName: 'Hydrangea macrophylla',
    category: 'kerti',
    location: 'kültéri',
    price: 6990,
    salePrice: null,
    stock: 16,
    light: 'közepes',
    watering: 'gyakori',
    difficulty: 'haladó',
    currentHeightCm: 45,
    maxHeightCm: 150,
    currentPotCm: 24,
    petSafe: false,
    kidSafe: false,
    airPurifying: false,
    rating: 4.3,
    reviewsCount: 112,
    description:
      'Nagy, gömbölyű virágzata a talaj pH-jától függően kék vagy rózsaszín árnyalatú lehet. Cianogén glikozidokat tartalmaz, ezért lenyelve mérgező.',
  },
  {
    name: 'Kerti kakukkfű',
    latinName: 'Thymus vulgaris',
    category: 'fűszer',
    location: 'mindkettő',
    price: 890,
    salePrice: null,
    stock: 70,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 10,
    maxHeightCm: 30,
    currentPotCm: 10,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.5,
    reviewsCount: 139,
    description:
      'Alacsony növésű, erőteljesen illatozó mediterrán fűszernövény, amely a napos, száraz, jól átengedő talajú helyeket kedveli.',
  },
];

async function main(): Promise<void> {
  // Idempotency: clear existing rows first so re-running the seed doesn't
  // accumulate duplicates (out of scope to build a full upsert/versioning
  // system per the brief — a delete-then-insert is enough here).
  await prisma.product.deleteMany();
  await prisma.product.createMany({ data: products });

  console.log(`Seeded ${products.length} products.`);
}

main()
  .catch((error: unknown) => {
    console.error('Seed failed:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
